version: '3.5'

networks:
  belka_network:
    ipam:
      driver: default
      config: 
        - subnet: 172.18.0.0/16

volumes:
  postgres:
    external: True
  pgadmin:
    external: True

services:

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      belka_network:
        ipv4_address: 172.18.0.3
    ports:
      - "5432:5432"
    volumes:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    user: 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    networks:
      belka_network:
        ipv4_address: 172.18.0.4
    ports:
      - "81:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres